name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Publish code coverage results
        uses: codecov/codecov-action@v3
        with:
          file: 'coverage.cobertura.xml'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          # Example command to deploy to staging
          echo "Deploying to staging environment..."
          # Add your deployment commands here

  notifications:
    runs-on: ubuntu-latest
    if: failure() # Trigger this job only if any previous job fails
    needs: [build, deploy]

    steps:
      - name: Notify team of failure
        uses: dawidd6/action-slack@v3
        with:
          status: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
